version: "3.7"
services:
  pigeon-${color}:
    build:
      context: .
      dockerfile: Dockerfile
    image: pigeon:latest
    restart: on-failure:10
    container_name: ${color}-pigeon
    privileged: true
    ports:
      - "${port}:8089"
      - "${port2}:8088"
    expose:
      - "9001"
    environment:
      - TZ=Asia/Shanghai
    networks:
      ${color}:
        ipv4_address: ${ip}
    volumes:
      - ${path}/log:/app/log
    command: ./match-3-pigeon -env=dev

networks:
  ${color}:
    external: true
