version: "3.7"
services:
  pangu-${color}:
    build:
      context: .
      dockerfile: Dockerfile
    image: pangu:latest
    restart: on-failure:10
    container_name: ${color}-pangu
    privileged: true
    ports:
      - "${port}:3001"
    expose:
      - "3002"
    networks:
      ${color}:
        ipv4_address: ${ip}
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${path}/log:/app/log
    command: ./pangu -servertype=dev -cname=dev

networks:
  ${color}:
    external: true
